import { type ClassValue, clsx } from "clsx";
import { extendTailwindMerge } from "tailwind-merge";

const twMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      "bg-image": ["bg-stage-dots", "bg-graph-paper"],
    },
    theme: {
      font: ["display", "sans", "pixel"],
      tracking: ["pixel", "display", "display-tight", "display-tightest"],
      text: [
        "key",
        "label",
        "title-sm",
        "title",
        "title-lg",
        "wordmark-lg",
        "label-sm",
        "note",
        "control",
        "control-lg",
        "lead",
        "heading-sm",
        "heading",
        "heading-lg",
        "monogram",
        "monogram-lg",
        "headline",
        "display-sm",
        "display",
        "display-lg",
        "display-xl",
        "caption",
        "body",
        "stage-caption",
        "stage-body",
        "stage-lg",
        "stage-xl",
        "stage-2xl",
        "stage-3xl",
        "stage-4xl",
        "stage-display",
        "stage-word",
      ],
      radius: ["control", "field", "button", "card", "tile", "panel", "sticker", "key", "bar"],
      shadow: [
        "card-stage",
        "knob",
        "primary",
        "primary-sm",
        "tile-coral",
        "tile-violet",
        "tile-lime",
        "tile-sky",
        "card-word",
        "drop-coral",
        "drop-violet",
        "drop-lime",
        "drop-sky",
        "brutal-xs",
        "brutal-sm",
        "brutal",
        "brutal-md",
        "brutal-lg",
        "brutal-xl",
        "brutal-2xl",
        "brutal-3xl",
        "brutal-violet",
        "brutal-violet-2xl",
        "brutal-sun-2xl",
        "brutal-white",
      ],
      animate: ["pop-in", "timer-pulse"],
    },
  },
});

export const cn = (...inputs: ClassValue[]) => twMerge(clsx(inputs));
